config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :cities
  resources :cruises
  resources :ships do
    resources :cabins
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cabin.rb
# == Schema Information
#
# Table name: cabins
#
#  id           :integer          not null, primary key
#  level        :integer          not null
#  room         :string
#  is_available :boolean          default(TRUE)
#  ship_id      :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Cabin < ApplicationRecord
    belongs_to :ship
    validates :room , :level , presence: true
    validates :room , uniqueness: {scope: [:level , :ship_id]}
    
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  country    :string           not null
#  photo      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class City < ApplicationRecord
    
    has_and_belongs_to_many :cruises
    validates :name , :country  , presence: true
    validates :name , uniqueness: {scope: [:country]}
    
    
    
end

app/models/cruise.rb
# == Schema Information
#
# Table name: cruises
#
#  id         :integer          not null, primary key
#  name       :string
#  duration   :integer          default(0), not null
#  base_cost  :decimal(, )      default(0.0)
#  dates      :date             default([]), is an Array
#  ship_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cruise < ApplicationRecord
    has_and_belongs_to_many :cities
    belongs_to :ship
    validates :name , :duration , presence: true
    validates :name , uniqueness: {scope: [:name , :ship_id]}
    
end

app/models/ship.rb
# == Schema Information
#
# Table name: ships
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  photo      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ship  < ApplicationRecord
    
    has_many :cabins , dependent: :delete_all
    has_many :cruises , dependent: :delete_all
    validates :name  , presence: true
    validates :name  , uniqueness: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :string           default("user")
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_user
  
   
  private 
  def get_user
      @user = current_user
      @is_logged_in  = user_signed_in?
      @is_admin = @is_logged_in && @user.role == 'admin'
  end
  
  def auth_admin
      redirect_to root_url if !@is_admin    
  end
  
  
   def auth_user
       redirect_to root_url if !@is_user   
   end
  
  
end

app/controllers/cabins_controller.rb
class CabinsController < ApplicationController
  before_action :auth_admin

  def new
    @ship = Ship.find(params[:ship_id])
    @cabin = Cabin.new
  end

  def create
    @ship = Ship.find(params[:ship_id])
    @cabin = Cabin.new(params[:cabin].permit(:room, :level))
    @cabin.ship = @ship

    if @cabin.save
      redirect_to @ship
    else
      render 'new'
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    
     before_action :auth_admin
     
     def index
        @cities = City.all
     end
    
     def new 
         @city = City.new
     end 
     
     
     def create 
         @city = City.new(params[:city].permit(:name , :country , :photo))
         
         if @city.save
             redirect_to cities_path
         else 
             render 'new'
         end
         
         
     end 
     
     def destroy
        city = City.find(params[:id])
        city.destroy
        redirect_to cities_path
     end
     
end

app/controllers/cruises_controller.rb
class CruisesController < ApplicationController
  before_action :auth_admin


   def index
       @ships = Ship.all
       @cruises = Cruise.all
    end
  
  def new
    @ships = Ship.all
    @cruise = Cruise.new
  end

  def create
    
           @cruise = Cruise.new
           
           @cruise.name =  params[:cruise][:name]
           @cruise.duration = params[:cruise][:duration]
           @cruise.base_cost = params[:cruise][:base_cost]
           @cruise.ship_id = params[:cruise][:ship].to_i
           @cruise.dates = params[:cruise][:date].to_s.split(",").map{|str| Date.parse(str)}.to_a
        
    if @cruise.save
      redirect_to cruises_path
    else
      @ships = Ship.all
      render 'new'
    end
    
    
  end
 
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index
        
    end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
    
    before_action :auth_admin
    
    
    def index
       @ships = Ship.all
    end
    
    def destroy
    
    end
    
     def new 
         @ship = Ship.new
     end 
    
    def create 
         @ship = Ship.new(params[:ship].permit(:name , :photo))
         if @ship.save
             redirect_to ships_path
         else 
             render 'new'
         end
         
         
     end 
     
     def destroy
        ship = Ship.find(params[:id])
        ship.destroy
        redirect_to ships_path
     end
     
     def show
        @ship = Ship.find(params[:id])
     end
     
     def showcruises
        @ship = Ship.find(params[:id])
        
     end
     
     
     def cabin_create
     end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_alerts.html.erb
<% if notice || alert %>
  <div class="border border-warning rounded p-2 m-2">
    <h4>Authentication</h4>
    <p class="text-info"><%= notice %></p>
    <p class="text-danger"><%= alert %></p>
  </div>
<% end %>

app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="border border-danger rounded p-2">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-dark">
  <span class="navbar-text">
      (c) 2017 Galvanize, Inc.
  </span>
</nav>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Carnival</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if !@is_logged_in %>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_in"><i class="fa fa-recycle"></i> Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_up"><i class="fa fa-plus-circle"></i> Register</a>
        </li>
      <% elsif @is_admin %>
        <li class="nav-item">
          <a class="nav-link" href="/cities"><i class="fa fa-truck"></i> Cities</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="/ships"><i class="fa fa-ship"></i> Ships</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="/cruises"><i class="fa fa-cruise"></i> Cruises</a>
        </li>
      <% elsif @is_user %>
      <% end %>

      <% if @is_logged_in %>
        <li class="nav-item">
          <a class="nav-link" href="/users/edit"><i class="fa fa-grav"></i> Profile</a>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
            <i class="fa fa-window-close"></i> <%= "#{@user.email} (#{@user.role})" %>
          <% end %>
        </li>
      <% end %>
  </div>
</nav>

app/views/cabins/new.html.erb
<h1 class="display-4 p-2">Add Cabin</h1>

<div class="row">
  <div class="col-4">
    <%= form_with(url: ship_cabins_path(@ship), model: @cabin, local: true) do |form| %>

      <%= render 'errors', object: @cabin %>

      <div class="form-group">
        <%= form.label :room %>
        <%= form.text_field :room, id: :cabin_room, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :level %>
        <%= form.text_field :level, id: :cabin_level, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
  <div class="col-8"></div>
</div>

app/views/cities/index.html.erb
<h1 class="display-4 p-2">Cities</h1>

<a href="/cities/new" class="btn btn-outline-primary m-2">
  <i class="fa fa-plus-circle"></i> New City
</a>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th></th>
      <th>Id</th>
      <th>Name</th>
      <th>Country</th>
      <th>Photo</th>
      </tr>
  </thead>
  <tbody>
    <% @cities.each do |c| %>
      <tr>
        <td>
          <%= link_to city_path(c), method: :delete do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
        <td><%= c.id %></td>
        <td><%= c.name %></td>
        <td><%= c.country %></td>
        <td><%= image_tag(c.photo, width: 75, height: 75, class: 'img-thumbnail') if c.photo %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/cities/new.html.erb
<h1 class="display-4 p-2">Add City</h1>

<div class="row">
  <div class="col-4">
    <%= form_with(model: @city, local: true) do |form| %>

      <%= render 'errors', object: @city %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :city_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :country %>
        <%= form.text_field :country, id: :city_country, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :photo %>
        <%= form.text_field :photo, id: :city_photo, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
  <div class="col-8"></div>
</div

app/views/cruises/index.html.erb
<h1 class="display-4">Cruises</h1>


<a href="/cruises/new" class="btn btn-outline-primary m-2">
  <i class="fa fa-plus-circle"></i> New Cruise </a>




<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Duration</th>
      </tr>
  </thead>
  <tbody>
    <% @cruises.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.name %></td>
        <td><%= c.duration %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/cruises/new.html.erb
<h1 class="display-4 p-2">Add Cruise</h1>

<div class="row">
  <div class="col-4">
    <%= form_with(model: @cruise, local: true) do |form| %>

      <%= render 'errors', object: @cruise %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :cruise_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :cost %>
        <%= form.text_field :cost, id: :cruise_cost, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :duration %>
        <%= form.text_field :duration, id: :cruise_duration, class: 'form-control' %>
      </div>

       <div class="field">
           <%= form.label :ships %>
           <%= form.select(:ship, id: :cruise_ship) do %>
               <% @ships.each do |ship| %>
                   <%= content_tag(:option, ship.name, value: ship.id) %>
               <% end %>
           <% end %>
       </div>
    
    
    
      <div class="form-group">
        <%= form.label :date %>
        <%= form.text_field :date, id: :cruise_date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
  <div class="col-8"></div>
</div

app/views/home/index.html.erb
my index page 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carnival</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'nav' %>
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <%= render 'alerts' %>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'footer' %>
  </body>
</html>

app/views/ships/index.html.erb
<h1 class="display-4 p-2">Ships</h1>

<a href="/ships/new" class="btn btn-outline-primary m-2">
  <i class="fa fa-plus-circle"></i> New Ship
</a>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th></th>
      <th>Id</th>
      <th>Name</th>
      <th>Photo</th>
      </tr>
  </thead>
  <tbody>
    <% @ships.each do |s| %>
      <tr>
        <td>
          <%= link_to ship_path(s), method: :delete do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
        <td><%= link_to s.id, ship_path(s) %></td>
        <td><%= s.name %></td>
        <td><%= image_tag(s.photo, width: 75, height: 75, class: 'img-thumbnail') if s.photo %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/ships/new.html.erb
<h1 class="display-4 p-2">Add Ship</h1>

<div class="row">
  <div class="col-4">
    <%= form_with(model: @ship, local: true) do |form| %>

      <%= render 'errors', object: @ship %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :ship_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :photo %>
        <%= form.text_field :photo, id: :ship_photo, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
  <div class="col-8"></div>
</div

app/views/ships/show.html.erb
<h1 class="display-4">Cabins for <%= @ship.name %></h1>


<%= link_to new_ship_cabin_path(@ship), class: 'btn btn-outline-primary' do %>
  <i class="fa fa-plus-circle"></i> Add Cabin</a>
<% end %>

<%= image_tag(@ship.photo, width: 250, height: 250, class: 'img-thumbnail') if @ship.photo %>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>Id</th>
      <th>Room</th>
      <th>Level</th>
      <th>Available?</th>
      </tr>
  </thead>
  <tbody>
    <% @ship.cabins.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.room %></td>
        <td><%= c.level %></td>
        <td><%= c.is_available %></td>
        </tr>
      <% end %>
  </tbody>
</table>